; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core2]
platform = espressif32
; platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#f9cddfde697b659b9e818ec514f1505d2bd4a8ae
board = m5stack-core2
framework = arduino
lib_deps = 
	m5stack/m5unified@^0.2.7
	; earlephilhower/ESP8266Audio@^2.4.1
	earlephilhower/BackgroundAudio@^1.4.4
monitor_speed = 115200
upload_speed = 921600
;build_flags = -D LV_CONF_INCLUDE_SIMPLE -I src
